### ISSUE TITLE
syntax highlight confusion

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy-language-server#166] opened 2021-08-12 12:20 UTC
The top screenshot has correct syntax, but the highlighting becomes confused. Removing the single quote in the end of first line (and breaking the statement) "fixes" this.

![ramclustr_xml_—_recetoxtools__Workspace_](https://user-images.githubusercontent.com/1814954/129195458-8260dac8-38b3-4827-b36a-90de84802af3.png)
![ramclustr_xml_—_recetoxtools__Workspace_](https://user-images.githubusercontent.com/1814954/129195489-644b5748-48f3-4052-85f9-c53a5996cb82.png)

**Comment by davelopez** [comment] 2021-08-12 14:55
Thank you @martenson for reporting! I will have a look, probably caused by some error in the regular expressions that highlight the code, sometimes those are hard to debug :sweat_smile:

**Comment by martenson** [comment] 2021-08-12 15:15
in case full code helps debug: https://github.com/RECETOX/galaxytools/blob/master/tools/ramclustr/ramclustr.xml

**Comment by davelopez** [comment] 2021-08-12 15:49
Thanks for providing the full source! It looks like one of the single quotes is unbalanced probably between lines 12 and 15 and starts mixing cheetah code with the string, if you count the single quotes in the document there are 7, so one is definitely missing somewhere, can you double-check where is the missing one?

![syntax](https://user-images.githubusercontent.com/46503462/129227347-42781280-3d6b-49ea-b4f1-30c81ae375fb.png)

**Comment by martenson** [comment] 2021-08-12 16:18
@davelopez it is not missing one I think. Only one from the if-else is printed for a total of 6
@bgruening yeah ;)

**Comment by davelopez** [comment] 2021-08-12 17:02
> @davelopez it is not missing one I think. Only one from the if-else is printed for a total of 6

Ohh I see now, then I'm afraid this kind of situation is not supported in the syntax highlighting defined in the grammar, they require the opening and closing quotes to match AFAIK :(

Your best bet here is what @bgruening suggest

**Comment by martenson** [comment] 2021-08-12 17:10
Makes sense. I'd be surprised if there was an easy solution. Feel free to close as #wontfix and thanks for looking into it.

**Closed** 2021-08-12 17:11 UTC
Labels: bug, wontfix, vscode extension
